name: Issues Auto Commenter

on: 
  issues: 
    types: [opened]
    


jobs: 
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: dumb Github information
      run: echo '${{toJson(github)}}' | jq